In [51]:
#배추가격 예측 데이터 
import numpy as np 

xy = np.loadtxt('../데이터/price_data.csv',delimiter=',',dtype=np.float32) #데이터 읽기


x_data = xy[:,1:-1] #전체 n개 를 1부터 -1 전까지 x 데이터 가져오기
y_data = xy[:,[-1]] #y 데이터 가져오기 
print(x_data,y_data)
print(len(x_data),len(y_data)) # 데이터 개수 확인 

[[ -4.9 -11.    0.9   0. ]
 [ -3.1  -5.5   5.5   0.8]
 [ -2.9  -6.9   1.4   0. ]
 ...
 [  2.9  -2.1   8.    0. ]
 [  2.9  -1.6   7.1   0.6]
 [  2.1  -2.    5.8   0.4]] [[2123.]
 [2123.]
 [2123.]
 ...
 [2901.]
 [2901.]
 [2901.]]
2922 2922


In [48]:
import tensorflow as tf
tf.set_random_seed(10)  # 난수 시드 설정


X=tf.placeholder(tf.float32,shape=[None,4])   #shape 주의 

Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([4,1]))  # 4x1 행렬 

b=tf.Variable(tf.random_normal([1]))

hypothesis = tf.matmul(X,W)+b        #행렬 곱 

cost = tf.reduce_mean(tf.square(hypothesis-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.00115)

train = optimizer.minimize(cost)

sess= tf.Session()

sess.run(tf.global_variables_initializer())

for i in range(150001):
    vcost,_ = sess.run([cost,train] ,feed_dict={X:x_data,Y:y_data})
    if i%2500==0:
        print(i,vcost)


0 12827995.0
2500 2053036.6
5000 1944653.2
7500 1889792.0
10000 1860741.0
12500 1844956.2
15000 1836260.4
17500 1831434.0
20000 1828745.5
22500 1827244.6
25000 1826407.2
27500 1825938.6
30000 1825676.1
32500 1825530.0
35000 1825447.8
37500 1825401.8
40000 1825376.4
42500 1825361.9
45000 1825354.1
47500 1825349.6
50000 1825347.2
52500 1825346.0
55000 1825345.4
57500 1825344.2
60000 1825344.2
62500 1825344.0
65000 1825343.6
67500 1825343.6
70000 1825344.0
72500 1825344.2
75000 1825344.0
77500 1825344.0
80000 1825344.0
82500 1825344.0
85000 1825344.0
87500 1825344.0
90000 1825344.0
92500 1825344.0
95000 1825344.0
97500 1825344.0
100000 1825344.0
102500 1825344.0
105000 1825344.0
107500 1825344.0
110000 1825344.0
112500 1825344.0
115000 1825344.0
117500 1825344.0
120000 1825344.0
122500 1825344.0
125000 1825344.0
127500 1825344.0
130000 1825344.0
132500 1825344.0
135000 1825344.0
137500 1825344.0
140000 1825344.0
142500 1825344.0
145000 1825344.0
147500 1825344.0
150000 1825344.0


In [50]:
avgTemp=float(input('평균기온 :'))
minTemp=float(input('최저기온 :'))
maxTemp=float(input('최고기온 :'))
rainFall=float(input('강수량 :'))
k=[avgTemp,minTemp,maxTemp,rainFall]
price = sess.run(hypothesis,feed_dict={X:[k]})
print("price :",price)


평균기온 :-2.7
최저기온 :-6.6
최고기온 :2.
강수량 :0.1
price : [[2924.2476]]
