In [1]:
import tensorflow as tf

In [9]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],
         [1,2,5,6],[1,6,6,6],[1,7,7,7]]

y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]


X = tf.placeholder(tf.float32 , shape = [None ,4 ])
Y = tf.placeholder(tf.float32 , shape = [None , 3])

W = tf.Variable(tf.random_normal([4,3]))  # 4(x 데이터) * 3(class a,b,c) 행렬 
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
#cross entropy 
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis =1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1)

train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for i in range(50001):
    c_val , _ = sess.run([cost,train],feed_dict={X:x_data , Y:y_data})
    if i%5000 ==0:
        print(i,c_val)

0 7.8778896
5000 0.074817814
10000 0.039564863
15000 0.026792914
20000 0.020229548
25000 0.016240172
30000 0.013561226
35000 0.011638963
40000 0.010192941
45000 0.009066051
50000 0.008163027


In [14]:
#출력 
a = sess.run(hypothesis,feed_dict={X:[[1,11,7,9]]})
print(a,sess.run(tf.arg_max(a,1)))
print('---------------')
b = sess.run(hypothesis,feed_dict={X:[[1,3,4,3]]})
print(b,sess.run(tf.arg_max(b,1)))
print('---------------')
c = sess.run(hypothesis,feed_dict={X:[[1,1,0,1]]})
print(c,sess.run(tf.arg_max(c,1)))
print('---------------')
allf = sess.run(hypothesis,feed_dict={X:[[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
print(allf,sess.run(tf.arg_max(allf,1)))  # max 함수 
print('---------------')

[[5.8155890e-11 1.0000000e+00 1.7127168e-10]] [1]
---------------
[[9.9994528e-01 5.3702825e-05 9.7428710e-07]] [0]
---------------
[[7.9704431e-24 7.3797507e-10 1.0000000e+00]] [2]
---------------
[[5.8156108e-11 1.0000000e+00 1.7127298e-10]
 [9.9994528e-01 5.3702926e-05 9.7428904e-07]
 [7.9704423e-24 7.3797507e-10 1.0000000e+00]] [1 0 2]
---------------
