In [13]:
import numpy as np
import tensorflow as tf

In [17]:
sess = tf.InteractiveSession()  #세션설정

In [6]:
#1D array
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)  #rank 
print(a.shape)  # shape
print(a[0],a[-1]) #첫번째, 마지막
print(a[0:2],a[:-2]) #슬라이싱 0~1 , 0~3 

[1 2 3 4 5]
1
(5,)
1 5
[1 2] [1 2 3]


In [11]:
#2D array 
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.ndim)  #rank
print(b.shape) # shape
print(b[2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
[7 8 9]


In [20]:
t = tf.constant([1,2,3,4]) # 1차원
tf.shape(t).eval()

array([4])

In [25]:
s =tf.constant([[1,2],[3,4],[5,6]]) # 2차원 3*2
tf.shape(s).eval()

array([1, 3, 2])

In [24]:
t = tf.constant
([# 축 0
    [ #1 축1
        [ #2 축 2
         [1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]  # 밑으로 3 축은 3
        ],
        [
         [13, 14, 15, 16], # -> 4
         [17, 18, 19, 20],
         [21, 22, 23, 24]
        ]
    ]
])
tf.shape(t).eval()
#AXIS 축??   제일 안쪽 -> 3 

array([1, 2, 3, 4])

In [27]:
# matmul vs multiply 
mx1 = tf.constant([[1,2],[3,4]]) # 2*2
mx2 = tf.constant([[1],[2]]) #2 *1
tf.matmul(mx1,mx2).eval() # 2*1

array([[ 5],
       [11]])

In [28]:
mx1 = tf.constant([[1,2],[3,4]]) # 2*2
mx2 = tf.constant([[1],[2]]) #2 *1
(mx1 *mx2).eval() # 2*1 ? 결과가 다르다 #broadcasting shape 안맞아도 연산됨 

array([[1, 2],
       [6, 8]])

In [30]:
#reduce_mean 평균 
tf.reduce_mean([1,3],axis = 0).eval()
#reduce_sum -> 누적합 axis 주의

2

In [34]:
#argmax  #반환 은 인덱스
x= [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval() #축->행 

array([1, 0, 0], dtype=int64)

In [35]:
tf.argmax(x, axis=1).eval()#축 -> 열 

array([2, 0], dtype=int64)

In [39]:
## RESHAPE 
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
print(t)
t.shape

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


(2, 2, 3)

In [43]:
tf.reshape(t,shape=[4,3]).eval() # 4대신 에 -1  3은 주로 건들지 않음

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
tf.reshape(t,shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [48]:
tf.squeeze([[0], [1], [2]]).eval() #줄임

array([0, 1, 2])

In [51]:
tf.expand_dims([0, 1, 2], 1).eval() #늘림 

array([[0],
       [1],
       [2]])

In [52]:
## ONE HOT 
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() # 100,010,001,100 #해당 인덱스에 1 아니면 0

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [55]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval() #100,010,001,100 을 행렬로 
#casting  형변환 , true false 도 0 1 로 (int 로 캐스팅)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
# axis 에 대한 이해 , 행렬 rank dim 에 대한 이해 필요